name: Shell Scripts CI

on:
  pull_request:
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'test/**'
      - 'Makefile'
      - '.github/workflows/shell-scripts.yml'
  push:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'test/**'
      - 'Makefile'
      - '.github/workflows/shell-scripts.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Install shfmt
        run: make install-shfmt

      - name: Check formatting
        run: make format-check

      - name: Run shellcheck
        run: make shellcheck

      - name: Run custom checks
        run: make custom-checks

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local

      - name: Run tests
        run: make test
